exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]
pygments: true

asset_pipeline:
  bundle: false            # Default = true
  compress: false          # Default = true
  output_path: assets     # Default = assets
  display_path: nil       # Default = nil
  gzip: false             # Default = false